version: '3.8'

services:
  nginx:
    build: ./srcs/nginx/
    container_name: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    networks:
      - inception

#############################################
  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
            - .env
    expose:
      - "3306"


#############################################

  wordpress:
    build: ./srcs/wordpress
    container_name: wordpress
    restart: always
    env_file:
            - .env
    volumes:
       - wordpress_data:/var/www/html
    networks:
      - inception
    expose:
      - "9000"


#############################################
volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
    driver: bridge


